::  Generated by frontend/tools/package_frontend.py. Do not hand edit.
|%
+$  asset  [spur=path size=@ud mime=@t]
++  files
  ^-  (map @t asset)
  %-  malt
  ^-  (list [@t asset])
  :~
    ['/apps/glurff/' /lib/glurff/site/index/html 595 'text/html; charset=utf-8']
    ['/apps/glurff/assets/index-25d52b2c.js' /lib/glurff/site/assets/index-25d52b2c/js 858.222 'application/javascript; charset=utf-8']
    ['/apps/glurff/characters/beard.png' /lib/glurff/site/characters/beard/png 15.745 'image/png']
    ['/apps/glurff/characters/body.png' /lib/glurff/site/characters/body/png 7.111 'image/png']
    ['/apps/glurff/characters/bottom.png' /lib/glurff/site/characters/bottom/png 4.948 'image/png']
    ['/apps/glurff/characters/gloves.png' /lib/glurff/site/characters/gloves/png 3.767 'image/png']
    ['/apps/glurff/characters/hair.png' /lib/glurff/site/characters/hair/png 41.242 'image/png']
    ['/apps/glurff/characters/hat.png' /lib/glurff/site/characters/hat/png 58.390 'image/png']
    ['/apps/glurff/characters/shoes.png' /lib/glurff/site/characters/shoes/png 4.319 'image/png']
    ['/apps/glurff/characters/shoulders.png' /lib/glurff/site/characters/shoulders/png 4.567 'image/png']
    ['/apps/glurff/characters/top.png' /lib/glurff/site/characters/top/png 29.959 'image/png']
    ['/apps/glurff/denoise-worklet.js' /lib/glurff/site/denoise-worklet/js 1.949.419 'application/javascript; charset=utf-8']
    ['/apps/glurff/favicon.png' /lib/glurff/site/favicon/png 2.784 'image/png']
    ['/apps/glurff/glurff-icon.png' /lib/glurff/site/glurff-icon/png 26.830 'image/png']
    ['/apps/glurff/index.html' /lib/glurff/site/index/html 595 'text/html; charset=utf-8']
    ['/apps/glurff/licenses/jitsi-license.html' /lib/glurff/site/licenses/jitsi-license/html 12.599 'text/html; charset=utf-8']
    ['/apps/glurff/licenses/rnnoise-license.html' /lib/glurff/site/licenses/rnnoise-license/html 1.623 'text/html; charset=utf-8']
    ['/apps/glurff/map/over.png' /lib/glurff/site/map/over/png 53.223 'image/png']
    ['/apps/glurff/map/vatican-over.png' /lib/glurff/site/map/vatican-over/png 11.062 'image/png']
    ['/apps/glurff/map/vatican.jpg' /lib/glurff/site/map/vatican/jpg 308.256 'image/jpeg']
    ['/apps/glurff/map/world.jpg' /lib/glurff/site/map/world/jpg 478.785 'image/jpeg']
    ['/apps/glurff/style.css' /lib/glurff/site/style/css 22.770 'text/css; charset=utf-8']
  ==
--
