"""Package an already-built frontend into an explicit local Glurff desk.
No ship commands, commits, syncs, network requests or deployment are performed.
"""
from pathlib import Path
import argparse,shutil,json,hashlib
p=argparse.ArgumentParser()
p.add_argument('--desk',type=Path,required=True)
a=p.parse_args()
root=Path(__file__).resolve().parents[1]
dist=root/'dist';desk=a.desk.resolve()
assert (dist/'index.html').is_file(), 'Run npm run build first'
assert (desk/'app/glurff.hoon').is_file(), 'Target must already be a Glurff desk'
content_types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.ico':'image/x-icon','.mp3':'audio/mpeg','.webmanifest':'application/manifest+json'}
files=sorted(p for p in dist.rglob('*') if p.is_file())
records=[]
written=set()
for f in files:
 rel=f.relative_to(dist)
 assert f.suffix in content_types,f'Unsupported asset: {rel}'
 assert all(part and all(c.islower() or c.isdigit() or c in '-_.' for c in part) for part in rel.parts),str(rel)
 clay_rel=Path(*[('asset-'+part.replace('_','')) if '_' in part else part for part in rel.parts])
 data=f.read_bytes();dest=desk/'lib/glurff/site'/clay_rel
 dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(data);written.add(dest)
 spur='/lib/glurff/site/'+str(clay_rel.with_suffix(''))+'/'+f.suffix[1:]
 record={'url':'/apps/glurff/'+str(rel),'spur':spur,'size':len(data),'mime':content_types[f.suffix],'sha256':hashlib.sha256(data).hexdigest()}
 records.append(record)
# This directory contains only generated frontend assets, never world/user data.
for old in (desk/'lib/glurff/site').rglob('*'):
 if old.is_file() and old not in written: old.unlink()
index=next(r for r in records if r['url']=='/apps/glurff/index.html')
entries=[dict(index,url='/apps/glurff/')]+records
text='''::  Generated by frontend/tools/package_frontend.py. Do not hand edit.
|%
+$  asset  [spur=path size=@ud mime=@t]
++  files
  ^-  (map @t asset)
  %-  malt
  ^-  (list [@t asset])
  :~\n'''
for r in entries:
 n=f"{r['size']:,}".replace(',','.')
 text+=f"    ['{r['url']}' {r['spur']} {n} '{r['mime']}']\n"
text+='  ==\n--\n'
(desk/'lib/glurff-assets.hoon').write_text(text)
(root/'site-manifest.json').write_text(json.dumps(entries,indent=2)+'\n')
print(f'Packaged {len(files)} assets; no ship commit performed.')
